//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class    IssueDetail
    {
        public int IssueDetailId { get; set; }
        public int IssueMasterId { get; set; }
        public int BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    
        public virtual IssueMaster IssueMaster { get; set; }
    }
}
