//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIssue
    {
        public int IssueId { get; set; }
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string IssueDate { get; set; }
    }
}
