//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int StudentId { get; set; }
        public string StudentRoll { get; set; }
        public string StudentName { get; set; }
        public string StudentGender { get; set; }
        public string StudentEmail { get; set; }
        public string StudentGrade { get; set; }
        public string StudentDep { get; set; }
    }
}
